_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 70

auto_lr_find: True
precision: 32
gradient_clip_val: 0

weights_summary: null
progress_bar_refresh_rate: 30
resume_from_checkpoint: null
