_target_: src.models.tcvae_resnet.betaTCVAE_ResNet

lr: 0.0001
momentum: 0.9
weight_decay: 1e-4

trainset_size: 50000
input_dim: 32
input_channels: 1
latent_dim: 10
anneal_steps: 200
is_mss: True

alpha: 1.0
beta: 4.0
gamma: 1.0
