_target_: src.datamodules.opg_datamodule.DentalImagingDataModule

data_dir: ${data_dir}
seed: ${seed}
batch_size: 1
num_workers: 10
pin_memory: True
resize: 256
molar_guarantee: True
considered_class: 1
labelled_size: 0.1