_target_: src.datamodules.opg_datamodule.DentalImagingDataModule

#data_dir: ${data_dir}/opg/ # data_dir is specified in config.yaml
data_dir: /cluster/scratch/jcarvalho/opg
seed: ${seed}
batch_size: 1
num_workers: 10
pin_memory: True
resize: 256
molar_guarantee: True
considered_class: 1
labelled_size: 0.1